### ISSUE TITLE
Workflow no longer working

### ISSUE THREAD

**Issue by roberdorfer** [mmazzarolo/alfred-jira-search#2]
Hi,

not really sure why this has started occuring (might be the change to zsh or some changes in big sur), but this workflow has stopped working for me.

The search no longer returns anything.

Happy to provide information that might help with debugging :)

**Comment by zcharleshebert** [comment]
Hello there, I really wanted to use this workflow so I fixed. I think the JIRA api changed so it broke how it was working previously. Can't really say because I'm new at using powerpacked Alfred.

**Comment by allienx** [comment]
This workflow still works, it's just the workflow file that you download from the releases is out-of-date with the latest code.

I've updated and exported the workflow with the latest `script-filter.sh` and environment variables. Had to `zip` to attach the file to this comment.

[alfred-jira-search.alfredworkflow.zip](https://github.com/mmazzarolo/alfred-jira-search/files/8051973/alfred-jira-search.alfredworkflow.zip)

**Comment by mmazzarolo** [comment]
Thank you @allienx :) I published a new release with your workflow
